services:
  queue-service:
    container_name: queue-service
    image: rabbitmq:3-management
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    ports:
      -  "5672:5672"
      -  "8999:8080"
      -  "15672:15672"
