// The greeting service definition.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: pkg/server/connections/grpc/pb/weapon.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Weapon_CreateWeapon_FullMethodName = "/pb.Weapon/CreateWeapon"
)

// WeaponClient is the client API for Weapon service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WeaponClient interface {
	CreateWeapon(ctx context.Context, in *CreateWeaponRequest, opts ...grpc.CallOption) (*CreateWeaponResponse, error)
}

type weaponClient struct {
	cc grpc.ClientConnInterface
}

func NewWeaponClient(cc grpc.ClientConnInterface) WeaponClient {
	return &weaponClient{cc}
}

func (c *weaponClient) CreateWeapon(ctx context.Context, in *CreateWeaponRequest, opts ...grpc.CallOption) (*CreateWeaponResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateWeaponResponse)
	err := c.cc.Invoke(ctx, Weapon_CreateWeapon_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WeaponServer is the server API for Weapon service.
// All implementations must embed UnimplementedWeaponServer
// for forward compatibility.
type WeaponServer interface {
	CreateWeapon(context.Context, *CreateWeaponRequest) (*CreateWeaponResponse, error)
	mustEmbedUnimplementedWeaponServer()
}

// UnimplementedWeaponServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWeaponServer struct{}

func (UnimplementedWeaponServer) CreateWeapon(context.Context, *CreateWeaponRequest) (*CreateWeaponResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateWeapon not implemented")
}
func (UnimplementedWeaponServer) mustEmbedUnimplementedWeaponServer() {}
func (UnimplementedWeaponServer) testEmbeddedByValue()                {}

// UnsafeWeaponServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WeaponServer will
// result in compilation errors.
type UnsafeWeaponServer interface {
	mustEmbedUnimplementedWeaponServer()
}

func RegisterWeaponServer(s grpc.ServiceRegistrar, srv WeaponServer) {
	// If the following call pancis, it indicates UnimplementedWeaponServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Weapon_ServiceDesc, srv)
}

func _Weapon_CreateWeapon_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateWeaponRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WeaponServer).CreateWeapon(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Weapon_CreateWeapon_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WeaponServer).CreateWeapon(ctx, req.(*CreateWeaponRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Weapon_ServiceDesc is the grpc.ServiceDesc for Weapon service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Weapon_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Weapon",
	HandlerType: (*WeaponServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateWeapon",
			Handler:    _Weapon_CreateWeapon_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/server/connections/grpc/pb/weapon.proto",
}
